language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- nightly
env:
  matrix:
  - DB=mysql
matrix:
  allow_failures:
  - php: nightly
before_script:
- phpenv config-rm xdebug.ini
script:
- phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd .. && zip -r com_ttlivescore.zip com_ttlivescore -x \*.git\* \*tests\* *travisci-phpunit.xml*
  *.travis.yml* *com_ttlivescore.xml*
deploy:
  provider: releases
  file: com_ttlivescore.zip
  skip_cleanup: true
  on:
    tags: true
  api_key: $GITHUB_API
after_deploy:
- curl -T com_ttlivescore/com_ttlivescore.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
