language: php
php:
- '5.6'
- '7.0'
- '7.1'
- nightly
env:
  matrix:
  - DB=mysql
  global:
  - secure: FmjFS8UDfgJrSBnGqWT/VLU4FLxs7hcRsfGDl63IYWrkY09Fk6iBNUVat8H23ep/iBfKtu6aHFVZL0jypLI09rYRDsnUoE2psj6gRxVmDXXTW/NBmVOWz/NWjZvhmxlULNgDZYS8ozRtrqpFytXNOU941Kivy3o20nayBc6JiN/VB/2pluA6B8om1uTxYzWFM4nurWRwT9NREuFAWUsyO0rFQPfSVn7AMYwjG+2fgOoA3l9nUtDZfTz8M132/yzcqAZHdaLwWASyH72d78r0JpzMepyLUSEfRF0nvBaGOfvCnSjfeJu6NcQd4MiK88TWJjSU8I4SH2vYAWiWGhCo/CW940zXBJwdbIhRcjoO7zf/OybQZ1y3fHYpI8puvRbrf7Ik0Kb2EVBUY3/5UeCIGUqc3QK5NbnAuG1rcaWbjkJ5dmlxCVZBcvX3Sx455yhlNMRIr/yQGvX1wEH4+pi0OdSOCHTQKij1GSatujiT/xXG3ApNVH3R4vekB82JIaL4awNaGURUeY/76vCNRYW5emqRBnOMTaFR23aGTRYMmOQ8ksSZ3J6I4Ywp7jldKD+UIi38M+AbnFN3tSMt69qfg3TahLlaJKiV6l1npjj8N1LlNRVbFBvqp2SSZfa0po0254TA88g0rq/VRABZJjKGxzeuhpCj8oH8TZgxgdvqWEY=
  - secure: H6qPN25NeCrV0goRPIdBcgW90Q+pcW12tBvjGpg7ixIHFQxl+qLLEY94hctmMk3+Jz5h/Hzo2FeZP8ciKKyrH1zobkg+7z/PMhMD66u+QTAyXPAMNeZ2G8BOmvH1p+fXitBcDoK/ARW9+OQwO6lb1QfAwXD0Q2BUkYEELKJRP7fS2rJJvDJtoq5JcjACbqqmkDO9ThBs2WyxnPnSBPpizS6HZayaVSIM0DlS/D5oXBlPundYRQelRGm7C9fC1ZuK0CaVJ3/iJhV+EL3GLfJZMNEsxvprydIP+R7LZP3BmHEYbhmDG6ISmqB3xIjYU5ky4GOD9FgDIoR5mGZtg7R1l1377T0YOK795rifLccrcfxt0zUkRmbmSYn+aqHNrNsCDLhqmI9YHL4VvkuAspruVTFbgPOwUEcsVNvyLk9E4nij4N/anR5xHuh+KL3EesQfL9BeZiovWH/NbDsJmAd/ZXpFqHrHTH0THKhZL6pwbFelxhT6fIzKCCoFqcGdnlzt9M3H1nS4qn5ObA1DFw+icL8ltdxqDiY0NdIeo0Uzlusr+ctCKKd34cAiXjG9hvm1h6OWnnBWV+i6y+9qbf3qpMO6IDkAuKLSY/uEWwyuMx3pACS2+iq3rJfStOXUztzIOGAR8DmcIh3CzMgsIwtZpss5Tni3S6YI6pVSbTKHeb4=
matrix:
  allow_failures:
  - php: nightly
before_script:
- phpenv config-rm xdebug.ini
script:
- phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd .. && zip -r com_ttlivescore.zip com_ttlivescore -x \*.git\* \*tests\* *travisci-phpunit.xml*
  *.travis.yml* *com_ttlivescore.xml*
deploy:
  provider: releases
  file: com_ttlivescore.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: RgtXG0/o4Ij80BD4/gNUVJMe/nd7+1M2qxag2cln70v1JhnpOYpf9gXfQ0/oqIyLG0uQuz1G2FXtOdeSXHbXb3z+htlUlrboJKkuZWyRiVafmxvaJB/NLZPHqlNpoC3ngzJABE09J2OfVfgvCphN8klGBSrX6Tc243lzsZKbKvnKHKJgdFCps+pp++jdjW0YlJye9b22fO2wuE0fr7dXUaROrNEIXAsXOziA+l4F83MVZugf3elH1ym/CPbn9BxErf/yucPt6SbNhv7fpqdqZh+7w/O79qKSeQ+Xa0FAhJD+xS5XvmMM8ROC8Z+vNbkLDYvBKhYFN/dN3XV8xqwXOEXzL15GDxV8Fa921Lhq13VlPcu5WYwd+U8O3WsNmFuDLsKOydMpM+Mdg+gFBdWjzqorbQ6WUcOQxzJD8Xw+Q8Yl3DHzjdOrEDxDTEwt4wnZPXakf0SI2QF+dt0yeykUOe8aKZrG3vBiQbuvOfafCzX09Lk1g2LcNBTKn4co7wkqxciZJd+9RJzZNY+JRoFphwW7pZxjptzDSsUoVsm9gDBU3fCAeNkX7e4fsSWJSufcddtGOAMWMXhQLG0r0SFXHujmjjnOJM0bTAPFYK93G1o70EMmAb/JJqtmv7hX7/DfxJs/pbcc4N49g7fADCoCSPdvcr7QMi2jxoztKbm08+s=
after_deploy:
- curl -T com_ttlivescore/com_ttlivescore.xml -u $FTP_USER:$FTP_PASSWORD ftp://gilebabe.webhosting.be/
