language: php

php: 
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

env:
  - DB=mysql

matrix:
  allow_failures:
    - php: nightly
 
before_script:
  - phpenv config-rm xdebug.ini
  - git clone https://github.com/joomla/joomla-cms.git joomla-cms

script:
  - phpunit --configuration travisci-phpunit.xml --no-configuration tests
