language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

env:
  - DB=mysql

matrix:
  allow_failures:
    - php: nightly

before_script:
  - phpenv config-rm xdebug.ini
  - git clone https://github.com/joomla/joomla-cms.git joomla-cms

script:
  - phpunit --configuration travisci-phpunit.xml --no-configuration tests

deploy:
  provider: releases
  api_key:
    secure: na4U0CUnnQED0pE03+A21MZkx8hXdfKeLRTg8JIpb3ZaYWmZ72D1WxOclFl40zYf39ZQkKG9yN0EtnDPqOVmiXjeSDL/q+7RTE0iZ+yBUHCZWYnUEwbI7Tx76XTHn6heOB5JeZMsmDpEhbQ0PHXdSVef7bWVehptDAlFFP1EK1b27Mlv9wHULf5dwlclnBV7jXy43WhRzBBtr+pGb3Y/BWR0ftceHreF2b46XA69ePhwkvE8TkNBpl4KAQMqwS5GfNLaX+9OZVnAxmoz5euNG7y+IvrepeBfQHXhe2nW6B7C00GZSgmQ+a9QmQEDin9vCxZJc16Oz+WkDyYw18R29YxmaaBkO3ZsAITwM5TkcMjk1UVuEwsuSy7zXa0gMK+wOnfPl0pnil5x8df1WvSeOR3OMYAsniMtNauk/uF6qPHbKmdw0lw+P76VxYX3Cgg/xF2ELHVBalYmITpuF9PpCdqNqxI06xoBJC/RzrkT1/t3gxSNN5o9pkdFDJIe2hSZy/nVQyVBWvMsI7abwYjiJBQGc0HtCInhPMH5TB7IlX8atQX5zut1ZpkEtZnSsfiTbXZEg8+OJrS8JORgtLxa4OjAI84ae8qaO8T69oT3Oh5lvsU3lSxzFga0okDCV2FNgzkLlzxLHIv2Jc92nYtAyNp0HMbmwhhHaTJq7LNlG3U=
  file: readme.md
  skip_cleanup: true
  on:
    tags: true
