language: php
php:
    - "5.6"
    - "7.0"
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"
    - nightly
jobs:
    allow_failures:
        - php: nightly
before_script:
    - composer require --dev phpunit/phpunit
    - composer require --dev phpunit/php-code-coverage
    - phpenv config-rm xdebug.ini
script:
    - ./vendor/bin/phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
    - cd .. && zip -r com_ttlivescore.zip/src com_ttlivescore -x \*.git\*
deploy:
    provider: releases
    file: com_ttlivescore.zip
    skip_cleanup: true
    on:
        tags: true
    api_key: $GITHUB_API
after_deploy:
    - curl -T com_ttlivescore/com_ttlivescore.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
