language: php
php:
- '5.6'
- '7.0'
- '7.1'
- nightly
env:
  matrix:
  - DB=mysql
  global:
  - secure: dNmFVRKRPTQM6Lv4bKePacd2ukYVsa+x8PtR8E4QzmLXXadLi8KtzCzVJYEa6iPwNKbxEvx/J9KJ2bKYRBEj1CWFUgFAd5iwD8rBZIcmLcICOYROaQfClKUg8jeagqkoyFYf1/X5vTLFHvkU/p7a27T2dHYQASQ6N4wIQo7Ppkdvpu5PflbzZ1CjMS8nXtweCnOiIXKMjxnmZgV9t74fq/3OkSzQrvjTXSzQMFGYObAe3GtkChTesGKDQ6zQB7ZPYKIm7upR4k1TAOcigacfVGiTQ3tdVCV4EatEp1U6w8LuICqMJeULQhtet5R7wOKx9aT784Oxcz5kcWRWcN8B8w56gXCHZub0sTWpb2cHBNLJCmdNldfIgdLnJEEbaWpeXbonIxd9YcDK7NyiMjnWXxnPl4I8xEuX62sHyNjodg6tyVOI9tRpjbAJeivO7mN9QQm8JTO5556YFQKqwa2gDW/ORak7stX2TfROCMUyQuci13RiGz6/jdZyTv8kfbaudZp1gWyuPjlJvWYmc/CThuH2vom8bgAAOM+QgkvsSfilFvwNiMikMrJB9kXUilaJnBvuHhAWmdgFUwkYOR0fOQOm+xwfapIFJZAODky4gayLtFEd4D0f9WX0HLQa1srbG2t+YkJZDfTdaWGXq+eXhdt3o8pqSIPF8ANmQ75ljwg=
  - secure: P4m9r2wVgUl2DTFbAW7hgBmQ8HLUOrhZDWy9MmyUI3es92mMSWJzzrOp4fzizE5qR8InO4QrqBrd1c3bX/5DI5mbZGKzmhozSnfm/ZyOKE5ZySLMny2L/+Dbp3l+MplfdoCy6FC9MfNtHlS8w4En+00Vc6f5Er/X9MS3/26Bzxfrxek+nE28jKE+hWzuZBzyMZkIWEQqVMu2E0xS1N60Q69fO2wMt4ksLZOBZrQkZuixv2yierQGPT2gvu0TOB6Lb/H4h5hKw69z+GSI0KIGmds1ZDaSNGkLvjm59Ysl0O2QjeprpmsnScFhVzmHnnu2qJxjgCiSfWTZWpfcve9KMR9pT6Gea+XL8fWLGZnaqek6u3c+ZHXtU1mMlHt3mb/dO4+puEnLjmUSI67aKCe/nx1DhYKyAMywFRS77C4HSwe2tclPOBpgoXcL083HSx3/BSrxYEwbjiGIjr1XeNydIKgt6mexhSB6h45fzSBd8GStWs3iewP6ElvXLKstykO+VpLL3VnrzsJnuqlH2rR8L8xlGBBCiSn4lAbEWwyindfoOD/zIouEFBJRxfJ+u7xfs+rUCG1HoofKBenZSLuD6RV5SYaUiw8RC8TcIC34kXGUgSuzFF92onWw7qPunpE6TT+wvaBxwBl9QUXSfTfT25zBrjb2ma+PN62y2Um7jRA=
matrix:
  allow_failures:
  - php: nightly
before_script:
- phpenv config-rm xdebug.ini
script:
- phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd .. && zip -r com_ttlivescore.zip com_ttlivescore -x \*.git\* \*tests\* *travisci-phpunit.xml*
  *.travis.yml* *com_ttlivescore.xml*
deploy:
  provider: releases
  file: com_ttlivescore.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: RgtXG0/o4Ij80BD4/gNUVJMe/nd7+1M2qxag2cln70v1JhnpOYpf9gXfQ0/oqIyLG0uQuz1G2FXtOdeSXHbXb3z+htlUlrboJKkuZWyRiVafmxvaJB/NLZPHqlNpoC3ngzJABE09J2OfVfgvCphN8klGBSrX6Tc243lzsZKbKvnKHKJgdFCps+pp++jdjW0YlJye9b22fO2wuE0fr7dXUaROrNEIXAsXOziA+l4F83MVZugf3elH1ym/CPbn9BxErf/yucPt6SbNhv7fpqdqZh+7w/O79qKSeQ+Xa0FAhJD+xS5XvmMM8ROC8Z+vNbkLDYvBKhYFN/dN3XV8xqwXOEXzL15GDxV8Fa921Lhq13VlPcu5WYwd+U8O3WsNmFuDLsKOydMpM+Mdg+gFBdWjzqorbQ6WUcOQxzJD8Xw+Q8Yl3DHzjdOrEDxDTEwt4wnZPXakf0SI2QF+dt0yeykUOe8aKZrG3vBiQbuvOfafCzX09Lk1g2LcNBTKn4co7wkqxciZJd+9RJzZNY+JRoFphwW7pZxjptzDSsUoVsm9gDBU3fCAeNkX7e4fsSWJSufcddtGOAMWMXhQLG0r0SFXHujmjjnOJM0bTAPFYK93G1o70EMmAb/JJqtmv7hX7/DfxJs/pbcc4N49g7fADCoCSPdvcr7QMi2jxoztKbm08+s=
after_deploy:
- curl -T com_ttlivescore/com_ttlivescore.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
