language: php

php: 
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

env:
  - DB=mysql

matrix:
  allow_failures:
    - php: nightly
 
before_script:
  - phpenv config-rm xdebug.ini
  - git clone https://github.com/joomla/joomla-cms.git joomla-cms

script:
  - phpunit --configuration travisci-phpunit.xml --no-configuration tests

deploy:
  provider: releases
  api_key: 
  	secure: SECURE_OAUTH_TOKEN
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    branch: travis-ci
    tags: true